name: Create and publish trnzt-home
on:
  push:
    branches: ["main"]

env:
  REGISTRY: codeberg.org
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: docker
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: https://github.com/docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha
      - name: Read Dockerfile
        id: dockerfile
        uses: https://github.com/andstor/file-reader-action@v1
        with:
          path: Dockerfile
      - uses: https://codeberg.org/thzinc/forgejo-kaniko-action@deea449ad63512522f0c8a092264f3209b27dc6c
        with:
          dockerfile: ${{ steps.dockerfile.outputs.contents }}
          image: ${{ steps.meta.outputs.tags }}
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGES_TOKEN }}
