name: Create and publish trnzt/home
on:
  push:
    branches: ["main"]
    tags:
      - "v*"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: azure/setup-helm@v4.3.0
        with:
          version: "v3.13.1"
        id: install
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ vars.PACKAGES_REGISTRY }}/${{ github.repository }}
            codeberg.org/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha
      - name: Login to local OCI registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.PACKAGES_REGISTRY }}
          username: ${{ secrets.PACKAGES_USERNAME }}
          password: ${{ secrets.PACKAGES_TOKEN }}
      - name: Login to Codeberg
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: codeberg.org
          username: ${{ secrets.CODEBERG_PACKAGES_USERNAME }}
          password: ${{ secrets.CODEBERG_PACKAGES_TOKEN }}
      - name: Create Kubeconfig
        run: |
          mkdir $HOME/.kube
          echo "${{ secrets.KUBECONFIG_BUILDX }}" > $HOME/.kube/config
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: kubernetes
          driver-opts: |
            namespace=buildx-builders
            qemu.install=true
      - name: Build and push container image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILDER_REGISTRY=${{ vars.PACKAGES_REGISTRY }}
      - name: Build Helm chart
        run: |
          helm package charts/trnzt-com --app-version "${{ fromJSON(steps.meta.outputs.json).['tag-names'][0] }}" --version "${{ fromJSON(steps.meta.outputs.json).['tag-names'][0] }}"
      - name: Push Helm chart
        run: |
          helm push "trnzt-com-${{ fromJSON(steps.meta.outputs.json).['tag-names'][0] }}.tgz" oci://${{ vars.PACKAGES_REGISTRY }}/trnzt
          helm push "trnzt-com-${{ fromJSON(steps.meta.outputs.json).['tag-names'][0] }}.tgz" oci://codeberg.org/trnzt
