when:
  - event: push
    branch: main
steps:
  - name: build_image
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: codeberg.org/trnzt/home
      registry: codeberg.org
      dockerfile: Dockerfile
      platforms: linux/amd64,linux/arm64/v8
      auto_tag: true
      username:
        from_secret: codeberg_package_username
      password:
        from_secret: codeberg_package_password
