when:
  - event: push
    branch: main
steps:
  - name: build_site
    image: codeberg.org/thzinc/jekyll:ruby-3.3.9-ghp-232
    commands:
      - bundle install
      - bundle exec jekyll build
  - name: build_image
    image: woodpeckerci/plugin-kaniko
    settings:
      repo: codeberg.org/trnzt/home
      registry: codeberg.org
      dockerfile: Dockerfile
      platforms: linux/arm64/v8
      auto_tag: true
      username:
        from_secret: codeberg_package_username
      password:
        from_secret: codeberg_package_password
