steps:
  - name: generate_docker_tags
    image: ghcr.io/dvjn/woodpecker-docker-tags-plugin
    settings:
      tags: |
        edge
        pr
        semver --format {{major}}
        semver --format {{major}}.{{minor}}
        semver --format {{version}}
        cron --format nightly-%Y%m%d
        sha
  - name: build_image
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: trnzt/home
      dockerfile: Dockerfile
      platforms: linux/amd64,linux/arm64/v8
      username:
        from_secret: codeberg_package_username
      password:
        from_secret: codeberg_package_password
